from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(6, -1, -1, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_8 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_8.setObjectName("txt_8")
        self.gridLayout.addWidget(self.txt_8, 2, 1, 1, 1)
        self.txt_6 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_6.setObjectName("txt_6")
        self.gridLayout.addWidget(self.txt_6, 1, 2, 1, 1)
        self.txt_4 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_4.setObjectName("txt_4")
        self.gridLayout.addWidget(self.txt_4, 1, 0, 1, 1)
        self.txt_5 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_5.setObjectName("txt_5")
        self.gridLayout.addWidget(self.txt_5, 1, 1, 1, 1)
        self.txt_9 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_9.setObjectName("txt_9")
        self.gridLayout.addWidget(self.txt_9, 2, 2, 1, 1)
        self.txt_7 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_7.setObjectName("txt_7")
        self.gridLayout.addWidget(self.txt_7, 2, 0, 1, 1)
        self.txt_2 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_2.setObjectName("txt_2")
        self.gridLayout.addWidget(self.txt_2, 0, 1, 1, 1)
        self.txt_3 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_3.setObjectName("txt_3")
        self.gridLayout.addWidget(self.txt_3, 0, 2, 1, 1)
        self.txt_1 = QtWidgets.QLineEdit(self.groupBox)
        self.txt_1.setObjectName("txt_1")
        self.gridLayout.addWidget(self.txt_1, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.final_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_2.setObjectName("final_2")
        self.gridLayout_2.addWidget(self.final_2, 0, 1, 1, 1)
        self.final_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_6.setObjectName("final_6")
        self.gridLayout_2.addWidget(self.final_6, 1, 2, 1, 1)
        self.final_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_3.setObjectName("final_3")
        self.gridLayout_2.addWidget(self.final_3, 0, 2, 1, 1)
        self.final_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_1.setObjectName("final_1")
        self.gridLayout_2.addWidget(self.final_1, 0, 0, 1, 1)
        self.final_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_5.setObjectName("final_5")
        self.gridLayout_2.addWidget(self.final_5, 1, 1, 1, 1)
        self.final_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_4.setObjectName("final_4")
        self.gridLayout_2.addWidget(self.final_4, 1, 0, 1, 1)
        self.final_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_7.setObjectName("final_7")
        self.gridLayout_2.addWidget(self.final_7, 2, 0, 1, 1)
        self.final_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_8.setObjectName("final_8")
        self.gridLayout_2.addWidget(self.final_8, 2, 1, 1, 1)
        self.final_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.final_9.setObjectName("final_9")
        self.gridLayout_2.addWidget(self.final_9, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_sol = QtWidgets.QPushButton(self.frame_3)
        self.btn_sol.setObjectName("btn_sol")
        self.horizontalLayout_2.addWidget(self.btn_sol)
        self.btn_clear = QtWidgets.QPushButton(self.frame_3)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_2.addWidget(self.btn_clear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.no_nodos_exp = QtWidgets.QLineEdit(self.frame_5)
        self.no_nodos_exp.setObjectName("no_nodos_exp")
        self.gridLayout_3.addWidget(self.no_nodos_exp, 1, 1, 1, 1)
        self.num_nodos_gen = QtWidgets.QLineEdit(self.frame_5)
        self.num_nodos_gen.setObjectName("num_nodos_gen")
        self.gridLayout_3.addWidget(self.num_nodos_gen, 2, 1, 1, 1)
        self.costo = QtWidgets.QLineEdit(self.frame_5)
        self.costo.setObjectName("costo")
        self.gridLayout_3.addWidget(self.costo, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Puzzle 8"))
        self.groupBox.setTitle(_translate("MainWindow", "Estado Inicial"))
        self.txt_8.setText(_translate("MainWindow", "0"))
        self.txt_6.setText(_translate("MainWindow", "0"))
        self.txt_4.setText(_translate("MainWindow", "0"))
        self.txt_5.setText(_translate("MainWindow", "0"))
        self.txt_9.setText(_translate("MainWindow", "0"))
        self.txt_7.setText(_translate("MainWindow", "0"))
        self.txt_2.setText(_translate("MainWindow", "0"))
        self.txt_3.setText(_translate("MainWindow", "0"))
        self.txt_1.setText(_translate("MainWindow", "0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Estado Final"))
        self.final_2.setText(_translate("MainWindow", "0"))
        self.final_6.setText(_translate("MainWindow", "0"))
        self.final_3.setText(_translate("MainWindow", "0"))
        self.final_1.setText(_translate("MainWindow", "0"))
        self.final_5.setText(_translate("MainWindow", "0"))
        self.final_4.setText(_translate("MainWindow", "0"))
        self.final_7.setText(_translate("MainWindow", "0"))
        self.final_8.setText(_translate("MainWindow", "0"))
        self.final_9.setText(_translate("MainWindow", "0"))
        self.btn_sol.setText(_translate("MainWindow", "Solucionar"))
        self.btn_clear.setText(_translate("MainWindow", "Limpiar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Solución "))
        self.label.setText(_translate("MainWindow", "Meta alcanzada"))
        self.label_4.setText(_translate("MainWindow", "Costo de ruta: "))
        self.label_2.setText(_translate("MainWindow", "El número de nodos expandidos: "))
        self.label_3.setText(_translate("MainWindow", "El número de nodos generados: "))